# Generated by Django 6.1 on 2026-08-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_worker_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='scheduler.project'),
        ),
    ]
