# Generated by Django 6.1 on 2026-08-23 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_worker_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_jobs', models.IntegerField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('failed_jobs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('failure_reason', models.CharField(max_length=100)),
                ('retry_count', models.IntegerField()),
                ('last_attempt_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('max_requests', models.IntegerField(default=100)),
                ('window_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('cron_expression', models.CharField(max_length=255)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('backoff_strategy', models.CharField(choices=[('FIXED', 'Fixed'), ('LINEAR', 'Linear'), ('EXPONENTIAL', 'Exponential')], default='FIXED', max_length=20)),
                ('backoff_delay', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobexecution',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-last_heartbeat']},
        ),
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='timeout_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worker',
            name='current_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SCHEDULED', 'Scheduled'), ('CLAIMED', 'Claimed'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DLQ', 'Dead Letter Queue')], db_index=True, default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['queue', 'status', 'scheduled_at'], name='scheduler_j_queue_i_6bcf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['batch_id'], name='scheduler_j_batch_i_5b5cae_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecution',
            index=models.Index(fields=['worker', 'started_at'], name='scheduler_j_worker__2df4f9_idx'),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='scheduler.project'),
        ),
        migrations.AddField(
            model_name='deadletterqueue',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entry', to='scheduler.job'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.jobexecution'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='scheduler.organization'),
        ),
        migrations.AddField(
            model_name='ratelimitrule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='scheduler.project'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='scheduler.queue'),
        ),
        migrations.AddField(
            model_name='workflowdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='scheduler.job'),
        ),
        migrations.AddField(
            model_name='workflowdependency',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='scheduler.job'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['created_at'], name='scheduler_d_created_13957d_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['execution', 'timestamp'], name='scheduler_j_executi_3f7c47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitrule',
            unique_together={('project', 'endpoint')},
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['is_active', 'next_run_at'], name='scheduler_s_is_acti_a24803_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdependency',
            index=models.Index(fields=['depends_on'], name='scheduler_w_depends_f779bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdependency',
            unique_together={('job', 'depends_on')},
        ),
    ]
